// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

// Defines values for MissingFieldsErrorError.
const (
	MissingFields MissingFieldsErrorError = "missing_fields"
)

// Defines values for PaymentRequestCurrency.
const (
	APT PaymentRequestCurrency = "APT"
)

// Defines values for PaymentSuccessResponseStatus.
const (
	Submitted PaymentSuccessResponseStatus = "submitted"
)

// Defines values for SimulationFailedErrorError.
const (
	SimulationFailed SimulationFailedErrorError = "simulation_failed"
)

// Defines values for TransactionConfirmedResponseStatus.
const (
	Confirmed TransactionConfirmedResponseStatus = "confirmed"
)

// Defines values for TransactionFailedResponseStatus.
const (
	Failed TransactionFailedResponseStatus = "failed"
)

// Defines values for TransactionNotFoundErrorError.
const (
	NotFound TransactionNotFoundErrorError = "not_found"
)

// Defines values for TransactionPendingResponseStatus.
const (
	Pending TransactionPendingResponseStatus = "pending"
)

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// MerchantAddress 商户地址
	MerchantAddress string `json:"merchant_address"`

	// PaymasterAddress 付费主地址（可选）
	PaymasterAddress *string `json:"paymaster_address,omitempty"`

	// Status 服务器状态
	Status string `json:"status"`
}

// MissingFieldsError defines model for MissingFieldsError.
type MissingFieldsError struct {
	// Error 错误类型
	Error MissingFieldsErrorError `json:"error"`

	// Message 错误消息
	Message string `json:"message"`

	// MissingFields 缺失的字段列表
	MissingFields []string `json:"missing_fields"`
}

// MissingFieldsErrorError 错误类型
type MissingFieldsErrorError string

// PaymentRequest defines model for PaymentRequest.
type PaymentRequest struct {
	// Amount 金额 uint类型
	Amount int64 `json:"amount"`

	// Currency 货币种类
	Currency *PaymentRequestCurrency `json:"currency,omitempty"`

	// Opt OPT hex格式
	Opt string `json:"opt"`

	// PayeeAddr 收款地址 hex格式
	PayeeAddr string `json:"payee_addr"`

	// PayerAddr 付款地址 hex格式
	PayerAddr string `json:"payer_addr"`
}

// PaymentRequestCurrency 货币种类
type PaymentRequestCurrency string

// PaymentSuccessResponse defines model for PaymentSuccessResponse.
type PaymentSuccessResponse struct {
	// Message 响应消息
	Message string `json:"message"`

	// Status 交易状态
	Status PaymentSuccessResponseStatus `json:"status"`

	// TransactionHash 交易哈希
	TransactionHash string `json:"transaction_hash"`
}

// PaymentSuccessResponseStatus 交易状态
type PaymentSuccessResponseStatus string

// SimulationFailedError defines model for SimulationFailedError.
type SimulationFailedError struct {
	// Details 具体错误信息
	Details string `json:"details"`

	// Error 错误类型
	Error SimulationFailedErrorError `json:"error"`

	// Message 错误消息
	Message string `json:"message"`
}

// SimulationFailedErrorError 错误类型
type SimulationFailedErrorError string

// TransactionConfirmedResponse defines model for TransactionConfirmedResponse.
type TransactionConfirmedResponse struct {
	// Currency 货币种类
	Currency string `json:"currency"`

	// Message 响应消息
	Message string `json:"message"`

	// ReceivedAmount 实际收到的金额
	ReceivedAmount string `json:"received_amount"`

	// Status 交易状态
	Status TransactionConfirmedResponseStatus `json:"status"`

	// Success 交易是否成功
	Success bool `json:"success"`

	// TransactionHash 交易哈希
	TransactionHash string `json:"transaction_hash"`
}

// TransactionConfirmedResponseStatus 交易状态
type TransactionConfirmedResponseStatus string

// TransactionFailedResponse defines model for TransactionFailedResponse.
type TransactionFailedResponse struct {
	// Error 错误信息
	Error string `json:"error"`

	// Message 响应消息
	Message string `json:"message"`

	// Status 交易状态
	Status TransactionFailedResponseStatus `json:"status"`

	// Success 交易是否成功
	Success bool `json:"success"`

	// TransactionHash 交易哈希
	TransactionHash string `json:"transaction_hash"`
}

// TransactionFailedResponseStatus 交易状态
type TransactionFailedResponseStatus string

// TransactionNotFoundError defines model for TransactionNotFoundError.
type TransactionNotFoundError struct {
	// Error 错误类型
	Error TransactionNotFoundErrorError `json:"error"`

	// Message 错误消息
	Message string `json:"message"`
}

// TransactionNotFoundErrorError 错误类型
type TransactionNotFoundErrorError string

// TransactionPendingResponse defines model for TransactionPendingResponse.
type TransactionPendingResponse struct {
	// Message 响应消息
	Message string `json:"message"`

	// Status 交易状态
	Status TransactionPendingResponseStatus `json:"status"`

	// TransactionHash 交易哈希
	TransactionHash string `json:"transaction_hash"`
}

// TransactionPendingResponseStatus 交易状态
type TransactionPendingResponseStatus string

// CreatePaymentJSONRequestBody defines body for CreatePayment for application/json ContentType.
type CreatePaymentJSONRequestBody = PaymentRequest
